routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ProductController@index');
Route::get('/backup/{type}', 'ProductController@backup')->name('backup');
Route::resource('product', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $timestamps = true;
    protected $fillable = [
        'name',
        'quantity',
        'price',
        'total',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use \Exception;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;
use JavaScript;
use Spatie\ArrayToXml\ArrayToXml;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('created_at', 'desc')->paginate(10);
        return view('Product/index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        JavaScript::put([
            'url_store_product' => route('product.store'),
            'url_products' => route('product.index'),
        ]);

        return view('Product/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     */
    public function store(Request $request)
    {
        try {
            //Validate
            $validator = Validator::make($request->all(), [
                'name' => 'bail|required|string|min:1|max:50|unique:products,name',
                'quantity' => 'required|numeric|min:1|max:999',
                'price' => 'required|numeric|min:1|max:9999',
            ]);

            if ($validator->fails()) {
                throw new ValidationException($validator);
            }

            Product::create([
                'name' => $request->name,
                'quantity' => $request->quantity,
                'price' => $request->price,
                'total' => $request->quantity * $request->price,
            ]);

            return response()->json(['errors' => false]);
        } catch (ValidationException $e) {
            $validator = $e->validator;
            $message = 'Validator fails.';
            if (($validator instanceof \Illuminate\Validation\Validator) && method_exists($e, 'errors')) {
                $message = implode(' ', $validator->errors()->all());
            }
            return response()->json(['errors' => true, 'description' => $message]);
        } catch (Exception $e) {
            return response()->json(['errors' => true, 'description' => $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        JavaScript::put([
            'url_update_product' => route('product.update', $product),
            'url_products' => route('product.index'),
            'product' => [
                'name' => $product->name,
                'price' => $product->price,
                'quantity' => $product->quantity,
            ]
        ]);

        return view('Product/edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        try {

            $validator = Validator::make($request->all(), [
                'name' => 'bail|required|string|min:1|max:50',
                'quantity' => 'required|numeric|min:1|max:999',
                'price' => 'required|numeric|min:1|max:9999',
            ]);

            if ($validator->fails()) {
                throw new ValidationException($validator);
            }

            $product->update([
                'name' => $request->name,
                'quantity' => $request->quantity,
                'price' => $request->price,
                'total' => $request->quantity * $request->price,
            ]);

            return response()->json(['errors' => false]);
        } catch (ValidationException $e) {
            $validator = $e->validator;
            $message = 'Validator fails.';
            if (($validator instanceof \Illuminate\Validation\Validator) && method_exists($e, 'errors')) {
                $message = implode(' ', $validator->errors()->all());
            }
            return response()->json(['errors' => true, 'description' => $message]);
        } catch (Exception $e) {
            return response()->json(['errors' => true, 'description' => $e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('product.index')->with(['info' => 'Product removed.']);
    }

    /**
     * Store all the Products in file
     * @param Request $request
     * @param string $type json|xml
     * @return mixed
     */
    public function backup(Request $request,$type='json')
    {
        try {
            $filename = 'products.json';
            $content = '';
            $products = Product::orderBy('created_at', 'desc')->get();
            switch ($type) {
                case 'xml':
                    $content = $this->storeXML($products);
                    $filename = 'products.xml';
                    break;
                default:
                    $content = json_encode($products);

            }
            Storage::put($filename, $content);
            return Storage::download($filename);
        }catch (Exception $e){
            abort(404,'File not found.');
        }
    }

    /**
     * @param $products
     * @return string $content
     */
    protected function storeXML($products)
    {
        $xml = new \SimpleXMLElement('<products/>');
        foreach($products as $v){
            $product = $xml->addChild('product');
            $product->addChild('id', $v->id);
            $product->addChild('name', $v->name);
            $product->addChild('price', $v->price);
            $product->addChild('quantity', $v->quantity);
            $product->addChild('total', $v->total);
        }
        return $xml->asXML();
    }
}

resources/views/Product/create.blade.php
@extends('layout')
@section('content')
    <create-product></create-product>
@endsection
@push('scripts')
    <script src="{{ mix('js/product/create.js') }}" ></script>
@endpush

resources/views/Product/edit.blade.php
@extends('layout')
@section('content')
    <edit-product></edit-product>
@endsection
@push('scripts')
        <script src="{{ mix('js/product/edit.js') }}" ></script>
@endpush

resources/views/Product/index.blade.php
@extends('layout')
@section('content')
    <div class="row" >
        <div class="col-12 text-right my-2">
            <span class="col-form-label" >Backup Database</span>
            <a href="{{ url('backup/xml') }}" class="btn btn-primary  btn-sm" >XML</a>
            <a href="{{ url('backup/json') }}" class="btn btn-primary  btn-sm" >JSON</a>
        </div>
    </div>
    <div class="table-responsive">
    <table class="table table-striped" >
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Total</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
                <tr>
                    <td>{{ $product->id }}</td>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->price }}</td>
                    <td>{{ $product->quantity }}</td>
                    <td>{{ $product->total }}</td>
                    <td>
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{ route('product.edit',$product) }}">Edit</a>
                                <form action="{{ URL::route('product.destroy', $product) }}" method="POST">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button type="submit" class="dropdown-item">Delete</button>
                                </form>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    </div>
    {{ $products->links() }}
@endsection

resources/views/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Error!</strong>
        <br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ (is_array($error)?var_export($error,true):$error) }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(request()->session()->has('info'))
    <div class="alert alert-info">
        <p>{{ session('info') }}<p>
    </div>
@endif

resources/views/header.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Paul Lopez</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url('/') }}" >Products <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('product.create') }}" >Create Product</a>
            </li>
        </ul>
    </div>
</nav>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ mix('css/app.css') }}" rel="stylesheet" media="all">

    {{--Additional Styles--}}
    @stack('styles')

</head>
<body>
@include('header')
<div class="container bg-light text-dark rounded">
    <div class="container-fluid w-100 p-2">
        @include('errors')
        <div id="app">
            {{-- Content--}}
            @yield('content')
        </div>
    </div>
</div>

    @include('javascript')
    <script src="{{ mix('js/app.js') }}" ></script>
    {{-- Additional Scripts--}}
    @stack('scripts')

</body>
</html>